[project]
name = "fastapi-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.4",
    "asgiref>=3.11.1",
    "asyncpg>=0.31.0",
    "bcrypt==4.0.1",
    "celery>=5.6.3",
    "fastapi-mail>=1.6.3",
    "fastapi[standard]>=0.136.0",
    "flower>=2.0.1",
    "itsdangerous>=2.2.0",
    "passlib>=1.7.4",
    "pydantic-settings>=2.14.0",
    "pyjwt>=2.12.1",
    "pytest>=9.0.3",
    "redis>=7.4.0",
    "schemathesis>=4.17.0",
    "setuptools>=82.0.1",
    "sqlmodel>=0.0.38",
    "uvicorn>=0.45.0",
]
